"""The installable-app module: everything a product needs to become an
Android app (Trusted Web Activity) without a line of native code.

Switched on by an `aplikace` section in data-manifest.json:

    "aplikace": {
      "balicek": "cz.simtegen.evidence_pneu",   # never changes once released
      "nazev": "Evidence pneu",                  # store title, <= 30 chars
      "kratky_nazev": "Pneu",                    # under the icon, <= 12 chars
      "popis": "Kde leží čí pneumatiky.",        # <= 80 chars
      "otisky": ["AB:CD:..."],                   # SHA-256 of the signing key(s)
      "pismeno": "E"                             # optional icon letter
    }

From that section this script writes, deterministically:

  web/manifest.webmanifest     name, colours, icons, and the Play package in
                               related_applications (the release workflow
                               reads the package from the LIVE manifest, so
                               the site is the single source of truth)
  web/.well-known/assetlinks.json
                               Digital Asset Links: Android shows the app
                               without a browser bar only when the site
                               vouches for the signing key. Empty `otisky`
                               is valid — the app then runs with a URL bar
                               until the owner copies the fingerprint from
                               Play Console (App integrity).
  web/sw.js, web/offline.html  a network-first service worker: online the
                               app is exactly the deployed site; offline it
                               shows the shell instead of Chrome's dinosaur.
                               It never touches /api/ — account data must
                               not outlive a session in a cache. It caches
                               only the site's own public files, not
                               anything about the customer.
  web/ikona-*.png              icons drawn from the design system (accent
                               colour, one letter), so no product ships the
                               "default icon" look and nobody has to draw.
  web/index.html               the manifest link and the worker registration
                               are inserted if missing (idempotent).

`zkontroluj(manifest)` is what CI runs (via kontrola_manifestu.py): the
files must equal what this script generates — a hand-edited worker is
drift, exactly like a hand-edited privacy policy. Icons are compared by
pixels, not bytes, because zlib builds differ between Windows and the CI
runner.

Stdlib only; the same file lives in both templates and is refreshed into
every product by the builder, like the policy generator.
"""

from __future__ import annotations

import json
import math
import re
import struct
import sys
import unicodedata
import zlib
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except (AttributeError, ValueError):
    pass

WEB = Path("web")
MANIFEST = Path("data-manifest.json")
ZNACKA = "<!-- aplikace: vykresli_aplikaci.py -->"
ODKAZ_MANIFESTU = '<link rel="manifest" href="/manifest.webmanifest">'
REGISTRACE = ('<script>if ("serviceWorker" in navigator) '
              'navigator.serviceWorker.register("/sw.js");</script>')
IKONY = (("ikona-192.png", 192, False), ("ikona-512.png", 512, False),
         ("ikona-maskable-512.png", 512, True))

BALICEK_VZOR = re.compile(r"^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*){2,}$")
OTISK_VZOR = re.compile(r"^([0-9A-F]{2}:){31}[0-9A-F]{2}$")

SW = """// Offline shell of the installed app. GENERATED by vykresli_aplikaci.py —
// do not edit; CI compares this file with the generator.
// Network first, always: online the app is exactly the deployed site and the
// cache only answers when the network does not. /api/ is never touched —
// account data must not outlive a session in a cache.
const SKORAPKA = "skorapka-v1";
const PREDEM = ["/", "/styl.css", "/offline.html", "/manifest.webmanifest", "/ikona-192.png", "/ikona-512.png"];

self.addEventListener("install", (udalost) => {
  udalost.waitUntil(caches.open(SKORAPKA).then((c) => c.addAll(PREDEM)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (udalost) => {
  udalost.waitUntil(
    caches.keys()
      .then((klice) => Promise.all(klice.filter((k) => k !== SKORAPKA).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (udalost) => {
  const pozadavek = udalost.request;
  const adresa = new URL(pozadavek.url);
  if (pozadavek.method !== "GET" || adresa.origin !== self.location.origin || adresa.pathname.startsWith("/api/")) {
    return;
  }
  udalost.respondWith(
    fetch(pozadavek)
      .then((odpoved) => {
        if (odpoved.ok && PREDEM.includes(adresa.pathname)) {
          const kopie = odpoved.clone();
          caches.open(SKORAPKA).then((c) => c.put(pozadavek, kopie));
        }
        return odpoved;
      })
      .catch(() => caches.match(pozadavek).then((ulozena) =>
        ulozena || (pozadavek.mode === "navigate" ? caches.match("/offline.html") : Response.error())))
  );
});
"""

OFFLINE = """<!doctype html>
<html lang="cs">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <meta name="theme-color" content="{barva}">
  <title>{nazev} — bez připojení</title>
  <link rel="stylesheet" href="styl.css">
</head>
<body class="appka">
  <main class="obrazovka aktivni">
    <div class="karta">
      <h1>Jste offline</h1>
      <p>{nazev} potřebuje připojení k internetu. Jakmile bude zpátky, stačí to zkusit znovu.</p>
      <button class="tlacitko" onclick="location.reload()">Zkusit znovu</button>
    </div>
  </main>
</body>
</html>
"""


# ── Inputs ────────────────────────────────────────────────────────────

def _barvy(styl: str) -> dict[str, str]:
    """Light-theme tokens from the first :root block of styl.css. The app's
    theme colour must be the product's accent, not a guess."""
    blok = re.search(r":root\s*\{(.*?)\}", styl, re.S)
    tokeny = dict(re.findall(r"--(barva-[a-z0-9-]+)\s*:\s*(#[0-9a-fA-F]{6})", blok.group(1) if blok else ""))
    return {
        "akcent": tokeny.get("barva-akcent", "#10504b").lower(),
        "akcent_text": tokeny.get("barva-akcent-text", "#ffffff").lower(),
        "pozadi": tokeny.get("barva-pozadi", "#f4f6f5").lower(),
    }


def _pismeno(aplikace: dict) -> str:
    zdroj = str(aplikace.get("pismeno") or aplikace.get("kratky_nazev") or aplikace.get("nazev") or "S")
    plain = unicodedata.normalize("NFKD", zdroj).encode("ascii", "ignore").decode().upper()
    for ch in plain:
        if ch in _GLYFY:
            return ch
    return "S"


# ── Icons: signed-distance rendering, stdlib only ─────────────────────

# Letters as strokes on a 4 x 6 grid (y down). Drawn as round-capped
# capsules, so they read as a clean monoline mark at any size.
_GLYFY: dict[str, list[list[tuple[float, float]]]] = {
    "A": [[(0, 6), (2, 0), (4, 6)], [(0.7, 4), (3.3, 4)]],
    "B": [[(0, 3), (0, 0), (2.8, 0), (3.8, 0.8), (3.8, 2.2), (2.8, 3), (0, 3)],
          [(0, 3), (0, 6), (3, 6), (4, 5.1), (4, 3.9), (3, 3)]],
    "C": [[(4, 1), (3, 0), (1, 0), (0, 1), (0, 5), (1, 6), (3, 6), (4, 5)]],
    "D": [[(0, 0), (0, 6), (2.4, 6), (4, 4.4), (4, 1.6), (2.4, 0), (0, 0)]],
    "E": [[(4, 0), (0, 0), (0, 6), (4, 6)], [(0, 3), (3, 3)]],
    "F": [[(4, 0), (0, 0), (0, 6)], [(0, 3), (3, 3)]],
    "G": [[(4, 1), (3, 0), (1, 0), (0, 1), (0, 5), (1, 6), (3, 6), (4, 5), (4, 3.4), (2.4, 3.4)]],
    "H": [[(0, 0), (0, 6)], [(4, 0), (4, 6)], [(0, 3), (4, 3)]],
    "I": [[(2, 0), (2, 6)], [(1, 0), (3, 0)], [(1, 6), (3, 6)]],
    "J": [[(4, 0), (4, 5), (3, 6), (1, 6), (0, 5)]],
    "K": [[(0, 0), (0, 6)], [(4, 0), (0, 3.6)], [(1.4, 2.4), (4, 6)]],
    "L": [[(0, 0), (0, 6), (4, 6)]],
    "M": [[(0, 6), (0, 0), (2, 3.2), (4, 0), (4, 6)]],
    "N": [[(0, 6), (0, 0), (4, 6), (4, 0)]],
    "O": [[(1, 0), (3, 0), (4, 1), (4, 5), (3, 6), (1, 6), (0, 5), (0, 1), (1, 0)]],
    "P": [[(0, 6), (0, 0), (3, 0), (4, 1), (4, 2), (3, 3), (0, 3)]],
    "Q": [[(1, 0), (3, 0), (4, 1), (4, 5), (3, 6), (1, 6), (0, 5), (0, 1), (1, 0)], [(2.6, 4.6), (4, 6)]],
    "R": [[(0, 6), (0, 0), (3, 0), (4, 1), (4, 2), (3, 3), (0, 3)], [(2, 3), (4, 6)]],
    "S": [[(4, 1), (3, 0), (1, 0), (0, 1), (0, 2), (1, 3), (3, 3), (4, 4), (4, 5), (3, 6), (1, 6), (0, 5)]],
    "T": [[(0, 0), (4, 0)], [(2, 0), (2, 6)]],
    "U": [[(0, 0), (0, 5), (1, 6), (3, 6), (4, 5), (4, 0)]],
    "V": [[(0, 0), (2, 6), (4, 0)]],
    "W": [[(0, 0), (1, 6), (2, 3), (3, 6), (4, 0)]],
    "X": [[(0, 0), (4, 6)], [(4, 0), (0, 6)]],
    "Y": [[(0, 0), (2, 3), (4, 0)], [(2, 3), (2, 6)]],
    "Z": [[(0, 0), (4, 0), (0, 6), (4, 6)]],
}


def _hex(barva: str) -> tuple[int, int, int]:
    return int(barva[1:3], 16), int(barva[3:5], 16), int(barva[5:7], 16)


def _vzdalenost_useck(px: float, py: float, useky: list[tuple[float, float, float, float]]) -> float:
    nejblize = 1e9
    for ax, ay, bx, by in useky:
        dx, dy = bx - ax, by - ay
        delka2 = dx * dx + dy * dy
        t = 0.0 if delka2 == 0 else max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy) / delka2))
        ex, ey = px - (ax + t * dx), py - (ay + t * dy)
        d = ex * ex + ey * ey
        if d < nejblize:
            nejblize = d
    return math.sqrt(nejblize)


def vykresli_ikonu(velikost: int, pismeno: str, barvy: dict[str, str], maskovatelna: bool) -> bytes:
    """Raw RGBA rows (with PNG filter byte 0) of one icon.

    Ordinary icon: rounded square in the accent colour, letter in the
    accent-text colour. Maskable: full-bleed square, letter inside the
    central safe zone Android masks to. Edges are anti-aliased from signed
    distances, which is exact and cheap enough in pure Python."""
    s = float(velikost)
    pozadi = _hex(barvy["akcent"])
    popredi = _hex(barvy["akcent_text"])
    vyska = s * (0.40 if maskovatelna else 0.50)
    meritko = vyska / 6.0
    sirka = 4.0 * meritko
    x0, y0 = (s - sirka) / 2.0, (s - vyska) / 2.0
    polomer_tahu = s * (0.040 if maskovatelna else 0.048)
    useky = []
    for tah in _GLYFY[pismeno]:
        for (ax, ay), (bx, by) in zip(tah, tah[1:]):
            useky.append((x0 + ax * meritko, y0 + ay * meritko, x0 + bx * meritko, y0 + by * meritko))
    okraj = polomer_tahu + 2
    lx0, lx1, ly0, ly1 = x0 - okraj, x0 + sirka + okraj, y0 - okraj, y0 + vyska + okraj
    zaobleni = s * 0.22
    polovina = s / 2.0

    radky = bytearray()
    for y in range(velikost):
        radky.append(0)
        py = y + 0.5
        for x in range(velikost):
            px = x + 0.5
            if maskovatelna:
                alfa = 1.0
            else:
                # Rounded-square signed distance.
                qx = abs(px - polovina) - (polovina - zaobleni)
                qy = abs(py - polovina) - (polovina - zaobleni)
                vne = math.hypot(max(qx, 0.0), max(qy, 0.0)) + min(max(qx, qy), 0.0) - zaobleni
                alfa = max(0.0, min(1.0, 0.5 - vne))
            pokryti = 0.0
            if lx0 <= px <= lx1 and ly0 <= py <= ly1:
                pokryti = max(0.0, min(1.0, 0.5 - (_vzdalenost_useck(px, py, useky) - polomer_tahu)))
            r = round(pozadi[0] + (popredi[0] - pozadi[0]) * pokryti)
            g = round(pozadi[1] + (popredi[1] - pozadi[1]) * pokryti)
            b = round(pozadi[2] + (popredi[2] - pozadi[2]) * pokryti)
            radky += bytes((r, g, b, round(alfa * 255)))
    return bytes(radky)


def png(velikost: int, radky: bytes) -> bytes:
    def blok(typ: bytes, data: bytes) -> bytes:
        return struct.pack(">I", len(data)) + typ + data + struct.pack(">I", zlib.crc32(typ + data) & 0xFFFFFFFF)
    hlavicka = struct.pack(">IIBBBBB", velikost, velikost, 8, 6, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n" + blok(b"IHDR", hlavicka)
            + blok(b"IDAT", zlib.compress(radky, 9)) + blok(b"IEND", b""))


def pixely_png(data: bytes) -> tuple[int, int, bytes] | None:
    """(width, height, raw rows) of a PNG we wrote — for comparing by pixels."""
    if not data.startswith(b"\x89PNG\r\n\x1a\n"):
        return None
    pos, sirka, vyska, idat = 8, 0, 0, b""
    while pos < len(data):
        delka = struct.unpack(">I", data[pos:pos + 4])[0]
        typ = data[pos + 4:pos + 8]
        obsah = data[pos + 8:pos + 8 + delka]
        if typ == b"IHDR":
            sirka, vyska = struct.unpack(">II", obsah[:8])
        elif typ == b"IDAT":
            idat += obsah
        pos += 12 + delka
    try:
        return sirka, vyska, zlib.decompress(idat)
    except zlib.error:
        return None


# ── Outputs ───────────────────────────────────────────────────────────

def _texty(manifest: dict, barvy: dict[str, str]) -> dict[Path, str]:
    a = manifest["aplikace"]
    nazev = str(a.get("nazev") or manifest.get("produkt") or "Aplikace")
    web_manifest = {
        "name": nazev,
        "short_name": str(a.get("kratky_nazev") or nazev)[:12],
        "description": str(a.get("popis") or ""),
        "lang": "cs",
        "dir": "ltr",
        "start_url": "/",
        "scope": "/",
        "display": "standalone",
        "orientation": "portrait",
        "background_color": barvy["pozadi"],
        "theme_color": barvy["akcent"],
        "icons": [
            {"src": "/ikona-192.png", "sizes": "192x192", "type": "image/png", "purpose": "any"},
            {"src": "/ikona-512.png", "sizes": "512x512", "type": "image/png", "purpose": "any"},
            {"src": "/ikona-maskable-512.png", "sizes": "512x512", "type": "image/png", "purpose": "maskable"},
        ],
        "related_applications": [{
            "platform": "play", "id": a["balicek"],
            "url": f"https://play.google.com/store/apps/details?id={a['balicek']}",
        }],
        "prefer_related_applications": False,
    }
    odkazy = [{
        "relation": ["delegate_permission/common.handle_all_urls"],
        "target": {"namespace": "android_app", "package_name": a["balicek"],
                   "sha256_cert_fingerprints": [str(o).upper() for o in a.get("otisky") or []]},
    }]
    return {
        WEB / "manifest.webmanifest": json.dumps(web_manifest, ensure_ascii=False, indent=2) + "\n",
        WEB / ".well-known" / "assetlinks.json": json.dumps(odkazy, indent=2) + "\n",
        WEB / "sw.js": SW,
        WEB / "offline.html": OFFLINE.format(nazev=nazev, barva=barvy["akcent"]),
    }


def _ikony(manifest: dict, barvy: dict[str, str]) -> dict[Path, tuple[int, bytes]]:
    pismeno = _pismeno(manifest["aplikace"])
    return {WEB / jmeno: (velikost, vykresli_ikonu(velikost, pismeno, barvy, maskovatelna))
            for jmeno, velikost, maskovatelna in IKONY}


def _index_s_odkazy(text: str) -> str:
    if ODKAZ_MANIFESTU not in text and "</head>" in text:
        text = text.replace("</head>", f"  {ZNACKA}\n  {ODKAZ_MANIFESTU}\n</head>", 1)
    if REGISTRACE not in text and "</body>" in text:
        text = text.replace("</body>", f"  {REGISTRACE}\n</body>", 1)
    return text


def _chyby_konfigurace(manifest: dict) -> list[str]:
    a = manifest.get("aplikace")
    if not isinstance(a, dict):
        return ["data-manifest.json: `aplikace` musí být objekt."]
    chyby = []
    if not BALICEK_VZOR.match(str(a.get("balicek") or "")):
        chyby.append("aplikace.balicek chybí nebo není platné jméno balíčku (např. cz.simtegen.evidence_pneu).")
    if not str(a.get("nazev") or "").strip() or len(str(a.get("nazev"))) > 30:
        chyby.append("aplikace.nazev musí mít 1–30 znaků (limit Google Play).")
    if len(str(a.get("kratky_nazev") or "")) > 12:
        chyby.append("aplikace.kratky_nazev smí mít nejvýš 12 znaků (vejde se pod ikonu).")
    if len(str(a.get("popis") or "")) > 80:
        chyby.append("aplikace.popis smí mít nejvýš 80 znaků (krátký popis v Google Play).")
    for otisk in a.get("otisky") or []:
        if not OTISK_VZOR.match(str(otisk).upper()):
            chyby.append(f"aplikace.otisky: „{str(otisk)[:40]}“ není SHA-256 otisk (32 párů hex oddělených dvojtečkou).")
    return chyby


def vykresli(manifest: dict) -> list[str]:
    """Write every output. Returns the paths written (empty = module off)."""
    if "aplikace" not in manifest:
        return []
    chyby = _chyby_konfigurace(manifest)
    if chyby:
        raise SystemExit("Modul aplikace: " + " ".join(chyby))
    barvy = _barvy((WEB / "styl.css").read_text(encoding="utf-8") if (WEB / "styl.css").exists() else "")
    zapsano = []
    for cesta, text in _texty(manifest, barvy).items():
        cesta.parent.mkdir(parents=True, exist_ok=True)
        cesta.write_text(text, encoding="utf-8", newline="\n")
        zapsano.append(str(cesta))
    for cesta, (velikost, radky) in _ikony(manifest, barvy).items():
        cesta.write_bytes(png(velikost, radky))
        zapsano.append(str(cesta))
    index = WEB / "index.html"
    if index.exists():
        puvodni = index.read_text(encoding="utf-8")
        novy = _index_s_odkazy(puvodni)
        if novy != puvodni:
            index.write_text(novy, encoding="utf-8", newline="\n")
            zapsano.append(str(index))
    return zapsano


def generovane_soubory(manifest: dict) -> set[Path]:
    """Files this module owns — the checkers skip them in their network and
    storage scans (the worker must fetch and cache), because zkontroluj()
    already proves they are exactly the generated ones."""
    if "aplikace" not in manifest:
        return set()
    return {WEB / "sw.js", WEB / "offline.html"}


def zkontroluj(manifest: dict) -> list[str]:
    """CI: the configuration is valid and every output equals the generator."""
    if "aplikace" not in manifest:
        return []
    chyby = _chyby_konfigurace(manifest)
    if chyby:
        return chyby
    barvy = _barvy((WEB / "styl.css").read_text(encoding="utf-8") if (WEB / "styl.css").exists() else "")
    for cesta, text in _texty(manifest, barvy).items():
        if not cesta.exists() or cesta.read_text(encoding="utf-8").replace("\r\n", "\n") != text:
            chyby.append(f"{cesta} neodpovídá manifestu — spusť `python vykresli_aplikaci.py` (ručně se needituje).")
    for cesta, (velikost, radky) in _ikony(manifest, barvy).items():
        pixely = pixely_png(cesta.read_bytes()) if cesta.exists() else None
        if pixely != (velikost, velikost, radky):
            chyby.append(f"{cesta} neodpovídá návrhovému systému — spusť `python vykresli_aplikaci.py`.")
    index = WEB / "index.html"
    if index.exists():
        text = index.read_text(encoding="utf-8")
        if ODKAZ_MANIFESTU not in text or REGISTRACE not in text:
            chyby.append("web/index.html nemá odkaz na manifest aplikace nebo registraci service workeru — "
                         "spusť `python vykresli_aplikaci.py`.")
    return chyby


def main() -> int:
    if not MANIFEST.exists():
        print("CHYBA: chybí data-manifest.json.")
        return 1
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    zapsano = vykresli(manifest)
    if not zapsano:
        print("Modul aplikace není zapnutý (v manifestu chybí sekce `aplikace`) — nic k vykreslení.")
        return 0
    print("Aplikace vykreslena:", ", ".join(zapsano))
    if not manifest["aplikace"].get("otisky"):
        print("Pozor: aplikace.otisky je prázdné — aplikace poběží s adresním řádkem, dokud tam "
              "nebude SHA-256 otisk podpisového klíče z Play Console (Integrita aplikace).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
